stages:
  - build
  - deploy

default:
  image: ubuntu:24.04
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get update
    # Klein, aber ausreichend für viele Standard-Dokumente
    - apt-get install -y --no-install-recommends \
        make latexmk texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended
    - rm -rf /var/lib/apt/lists/*

build_pdf:
  stage: build
  script:
    # -halt-on-error: bricht bei Fehlern ab; -pdf: baut PDF
    - latexmk -pdf -interaction=nonstopmode -halt-on-error main.tex
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - main.pdf

# Optional: GitLab Pages, um das PDF als "statische Website" anzubieten
pages:
  stage: deploy
  needs: ["build_pdf"]
  script:
    - mkdir -p public
    - cp main.pdf public/
    # Optional: eine Indexseite erzeugen
    - printf '<!doctype html><meta charset="utf-8"><title>PDF</title><p><a href="main.pdf">Download main.pdf</a>' > public/index.html
  artifacts:
    paths:
      - public
  rules:
    # Nur die Hauptbranch als "Website" veröffentlichen
    - if: '$CI_COMMIT_BRANCH == "main"'
