name: Build LaTeX PDF

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Variante A: fertiges TeX-Live-Image als Action (empfohlen, schnell & simpel)
      - name: Compile LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          latexmk_use_lualatex: false   # Standard: pdflatex
          extra_system_packages: ""     # z.B. 'biber' bei Bedarf

      # Ergebnis bereitstellen
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: main-pdf
          path: main.pdf
          retention-days: 7
